
TESTS= \
	Callchain \
	Callframe \
	InlineFrame \
	SharedPtr \
	SharedString \

TEST_CALLCHAIN_OBJS= \
	Callchain.o \
	Callframe.o \

TEST_CALLCHAIN_LIBS= \
	gmock

TEST_CALLFRAME_OBJS=Callframe.o

.include "gtest.mk"
